#!/bin/sh

set -euC

git rev-parse --verify HEAD >/dev/null 2>&1 \
	&& against=HEAD \
	|| against=$(git hash-object -t tree /dev/null)

# Make sure paths are portable.
if [ $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0 ]; then
	echo "Please limit to standard ASCII set for filenames for portability."
	exit 1
fi

# Make sure there are no diff markers.
git diff-index --check --cached $against --

exit 0
