#!/bin/sh
# $dotid$

export DISPLAY=:0
export PATH=$HOME/Local/bin:$PATH

_run() {
	local t=$(which $1 > /dev/null 2>&1)
	if [ $? -eq 0 ]; then
		$* >> /tmp/xsession-output 2>&1 &
	fi
}

cd ~

# X settings
_run xset -b
_run xmodmap ~/.Xmodmap
_run xbacklight -set 20
_run xsetroot -solid "#3a6ea5"
_run xrdb ~/.Xdefaults

# moused does this on FreeBSD much better than X
if [ $(uname -s) = FreeBSD ]; then
	_run xset m 1/1 1
else
	:
	# We use /etc/X11/xorg.conf.d/50-mouse.conf now
	#_run xset m 4/8 1
fi

_run trayer --edge bottom --align right --widthtype request --expand true
_run redshift-gtk
_run battray
_run volumeicon
_run dunst
# TODO: Seems to have problems?
#_run parcellite
xcape -e 'Control_L=Escape;Shift_L=KP_Add'

if [ -f ~/.xsession_local ]; then
	. ~/.xsession_local
fi
