ZDOTDIR=~/.zsh
umask 022

_exists() { hash $1 2>/dev/null }
_exists uname && uname=$(uname) || uname=win32

source ~/.zsh/env.zsh

# Our work here is done if not an interactive shell
[[ -o interactive ]] || exit 0

source ~/.zsh/settings.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/commands.zsh
source ~/.zsh/keys.zsh

unfunction _exists

# Other stuff to look at:
# https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/dircycle/dircycle.plugin.zsh
# https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/dirhistory/dirhistory.plugin.zsh
# https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/dirpersist/dirpersist.plugin.zsh
# https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/tmux
fpath=($fpath ~/.zsh/plugins)
source ~/.zsh/plugins/*.zsh

# We're ssh-ing into vagrant
if [[ -d /vagrant ]]; then
	#cd /vagrant
	#export TERM=xterm
	setopt ignoreeof         # Don't logout on ^D
fi

# Don't really need coredumps
limit coredumpsize 0

# I like fortunes!
fortune -a
