" Make sure we load stuff in the correct order − e.g. loading autocmd.vim before
" settings.vim can cause problems
source ~/.vim/settings.vim
source ~/.vim/autocmd.vim
source ~/.vim/commands.vim
source ~/.vim/keys.vim
source ~/.vim/macros.vim
source ~/.vim/gui.vim
source ~/.vim/softwrap.vim
source ~/.vim/completion.vim
source ~/.vim/experiments.vim
source ~/.vim/words.vim

" Plugin configs can be in any order.
for s:f in glob("$HOME/.vim/p-*.vim", 0, 1)
	execute 'source ' . s:f
endfor
