" $dotid$

call plug#begin('~/.vim/plugged')

" Easy visual undo tree (:UndotreeToggle or <F3>)
Plug 'mbbill/undotree'

" Add indentation 'guidelines' (:IndentLinesToggle or <F11>)
Plug 'Yggdroot/indentLine'

" Make it easy to make ASII tables (:TableModeToggle)
Plug 'dhruvasagar/vim-table-mode'

" Warn on syntax errors (enabled by default, disable with :SyntasticToggleMode)
" TODO: Configure C so it doesn't whine so much about missing header files
"Plug 'scrooloose/syntastic'

" Interpret colour escape codes (:AnsiEsc)
Plug 'vim-scripts/AnsiEsc.vim'

" Useful unicode related stuff (:SearchUnicode, :UnicodeName)
" TODO
Plug 'chrisbra/unicode.vim'

""" Filetypes
Plug 'groenewege/vim-less'        " LessCSS
Plug 'hail2u/vim-css3-syntax'     " Knows moar CSS rules
Plug 'hdima/python-syntax'        " Better Python syntax highlighting
Plug 'kchmck/vim-coffee-script'   " CoffeeScipt
Plug 'rodjek/vim-puppet'          " Puppet
Plug 'slim-template/vim-slim'     " Slim templates
Plug 'vim-ruby/vim-ruby'          " Better ruby motions, completions

"Plug 'SirVer/ultisnips'
"Plug 'honza/vim-snippets'
"Plug 'davidhalter/jedi-vim'
"Plug 'pangloss/vim-javascript'
"Plug 'mxw/vim-jsx'

call plug#end()


" Expanded % functionality
runtime macros/matchit.vim

" Load my vimrc files
for f in glob('~/.vim/*.vim', 0, 1)
	exe 'source ' . f
endfor
