# Store all zsh-related stuff in ~/.zsh/ instead of ~/
ZDOTDIR=~/.zsh
umask 022

# Helper stuff; will be unset later.
_exists() { hash $1 2>/dev/null }
_exists uname && uname=$(uname) || uname=win32
uid=$(id -u)

# Source config files.
source ~/.zsh/env.zsh
[[ -o interactive ]] || exit 0  # Our work here is done if not an interactive shell

source ~/.zsh/settings.zsh
source ~/.zsh/completion.zsh
source ~/.zsh/commands.zsh
source ~/.zsh/keys.zsh

# Unset helpers.
unfunction _exists
unset uid
unset uname

# Directory shortcuts
pack=$HOME/.cache/vim/pack/plugins/start/

# Source plugins.

# Other stuff to look at:
# https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/dircycle/dircycle.plugin.zsh
# https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/dirhistory/dirhistory.plugin.zsh
# https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/dirpersist/dirpersist.plugin.zsh
# https://github.com/robbyrussell/oh-my-zsh/tree/master/plugins/tmux
fpath=($fpath ~/.zsh/plugins)
for f in ~/.zsh/plugins/*.zsh; do source "$f"; done
