#!/bin/sh
#
# List emojis in dmenu; requires xclip and the "uni" tool from
# https://github.com/arp242/uni
#
# Usage:
#
#   dmenu-uni all            All codepoints, won't include ZWJ emoji sequences.
#   dmenu-uni emoji          All emojis.
#   dmenu-uni emoji-common   Common emojis
#
# NOTE: dmenu will *crash* when using a colour emoji font, this is a bug in Xft:
# https://bugs.freedesktop.org/show_bug.cgi?id=107534
#
# You can use this patch to fix it:
# https://gitlab.freedesktop.org/xorg/lib/libxft/-/merge_requests/1
echo " $@" | grep -q -- ' -h' && { sed '1,2d; /^[^#]/q; s/^# \?//;' "$0" | sed '$d'; exit 0; }  # Show docs
set -euC

dmenu="dmenu -x -i -l 20 -fn monospace:size=20 -sb #dddddd -sf #000000"
copy="xclip -rmlastnl -selection clipboard"
common="-or g:smileys g:hand-fingers-open g:hand-fingers-partial g:hand-single-finger g:hand-fingers-closed g:hands g:body-parts g:person-gesture"

case "${1:-all}" in
	all)           uni -q p all     | $dmenu | grep -o "^'.'" | tr -d "'" | $copy ;;
	emoji)         uni -q e all     | $dmenu | cut -d ' ' -f1 | $copy ;;
	emoji-common)  uni -q e $common | $dmenu | cut -d ' ' -f1 | $copy ;;
	*)             uni -q e $@      | $dmenu | cut -d ' ' -f1 | $copy ;;
	#*)             echo >&2 "dmenu-uni: unknown '$1'" ;;
esac
