#!/bin/sh
#
# Disable xbanish and xcape while a command is running.
echo " $@" | grep -q -- ' -h' && { sed '1,2d; /^[^#]/q; s/^# \?//;' "$0" | sed '$d'; exit 0; }  # Show docs
set -euC

trap 'sv start ~/.config/service/xcape ~/.config/service/xbanish' EXIT
sv stop ~/.config/service/xcape ~/.config/service/xbanish
"$@"
