#!/usr/bin/env zsh
#
# Frob with git so that "main" gets rewritten to "master" if that's the default
# branch, or vice versa.
#
# The "real" git is assumed to be in /usr/bin/git.
[ "${ZSH_VERSION:-}" = "" ] && echo >&2 "Only works with zsh" && exit 1
setopt err_exit no_unset no_clobber pipefail

def=${$(/usr/bin/git symbolic-ref refs/remotes/origin/HEAD >&/dev/null ||:):t}
if [[ $def = 'master' && $argv[(i)main] -le $#argv ]] then
	print >&2 "Using 'main' instead of 'master'"
	argv[$argv[(i)main]]=master
elif [[ $def = 'main' && $argv[(i)master] -le $#argv ]] then
	print >&2 "Using 'master' instead of 'main'"
	argv[$argv[(i)master]]=main
fi

exec /usr/bin/git $argv
