#!/usr/bin/env python
#
# Add times in the format of "1:15".

import datetime, sys

args = sys.argv[1:]
if len(args) == 0:
    args = sys.stdin.read().split(' ')

added = datetime.timedelta()
for a in args:
    h, m = a.split(':')
    added += datetime.timedelta(hours=int(h), minutes=int(m))

mins = added.total_seconds() / 60

print(added)
print(f'{int(mins // 60)}:{int(mins % 60)}')
