#!/bin/sh
#
# Start or switch to tmux session for goatcounter.
echo " $@" | grep -q -- ' -h' && { sed '1,2d; /^[^#]/q; s/^# \?//;' "$0" | sed '$d'; exit 0; }  # Show docs
set -euC

cd ~/code/goatcounter
s=goatcounter
att() {
	if [ -n "${TMUX:-}" ]; then
		tmux switch-client -t "=$s"
	else
		tmux attach-session -t "=$s"
	fi
}
if tmux has-session -t "=$s" 2> /dev/null; then
	att
	exit 0
fi
tmux new-session -d -s "$s"

tmux new-window -d -t "=$s" -n goatcounter
tmux send-keys -t "=$s:=goatcounter" \
	"goatcounter saas -dev -db 'postgresql+dbname=goatcounter' -listen localhost:8081 -websocket" Enter

att
